---
# tasks file for namrata-jenkins
#- hosts: all
# become: true
#tasks:

  - name: add jenkins key
    apt_key:
     url: "{{jenkins.jenkins_key}}"
     state: present
    become: yes

  - name: config debian repo
    apt_repository: 
     repo: deb http://pkg.jenkins.io/debian-stable binary/
     state: present
    become: yes

  - name: update
    apt: 
     update_cache: yes
     state: latest

  - name: Install java
    apt:
     state: present
     name: "{{java_pkg}}"

  - name: Install jenkins
    apt:
     state: latest
     name: jenkins

  
